using System.Reflection;
using System.Runtime.InteropServices;
using System.Web.UI;



[assembly: AssemblyTitle("EncyIG")]
[assembly: AssemblyDescription("Data Aquarium Framework application library")]
[assembly: AssemblyCompany("EncyIG")]
[assembly: AssemblyProduct("EncyIG Aquarium in the Box")]
[assembly: AssemblyCopyright("Copyright © EncyIG 2018")]
[assembly: ComVisible(false)]
[assembly: AssemblyVersion("1.0.*")]
[assembly: AssemblyFileVersion("1.0.0.0")]
[assembly: WebResource("EncyIG.js.sys._System.js", "text/javascript")]
[assembly: WebResource("EncyIG.js.sys.bootstrap.min.js", "text/javascript")]
[assembly: WebResource("EncyIG.js.sys.jquery-2.2.4.min.js", "text/javascript")]
[assembly: WebResource("EncyIG.js.sys.jquery.mobile-1.4.6.min.js", "text/javascript")]
[assembly: WebResource("EncyIG.js.daf.daf.min.js", "text/javascript")]
[assembly: WebResource("EncyIG.js.sys.unicode.min.js", "text/javascript")]
[assembly: WebResource("EncyIG.js.daf.daf-odp.min.js", "text/javascript")]
[assembly: WebResource("EncyIG.js.daf.touch-edit.min.js", "text/javascript")]
[assembly: WebResource("EncyIG.js.daf.touch-scroll.min.js", "text/javascript")]
[assembly: WebResource("EncyIG.js.daf.daf-resources.min.js", "text/javascript")]
[assembly: WebResource("EncyIG.js.daf.daf-resources.min.en_US.js", "text/javascript")]
[assembly: WebResource("EncyIG.js.sys.culture.en-US.js", "text/javascript")]
[assembly: WebResource("EncyIG.js.daf.daf-extensions.min.js", "text/javascript")]
[assembly: WebResource("EncyIG.js.daf.daf-menu.min.js", "text/javascript")]
[assembly: WebResource("EncyIG.js.sys.MicrosoftAjax.min.js", "text/javascript")]
[assembly: WebResource("EncyIG.js.sys.MicrosoftAjaxWebForms.min.js", "text/javascript")]
[assembly: WebResource("EncyIG.js.sys.AjaxControlToolkit.min.js", "text/javascript")]
[assembly: WebResource("EncyIG.js.daf.daf-membership.min.js", "text/javascript")]
[assembly: WebResource("EncyIG.Theme.Social.css", "text/css", PerformSubstitution=true)]
[assembly: WebResource("EncyIG.Theme.Acrobat.gif", "image/gif")]
[assembly: WebResource("EncyIG.Theme.ActionBarBg.gif", "image/gif")]
[assembly: WebResource("EncyIG.Theme.ActionBarDiv.gif", "image/gif")]
[assembly: WebResource("EncyIG.Theme.ActionGroupBg.gif", "image/gif")]
[assembly: WebResource("EncyIG.Theme.AddBookmark.gif", "image/gif")]
[assembly: WebResource("EncyIG.Theme.AdvancedSearch.gif", "image/gif")]
[assembly: WebResource("EncyIG.Theme.arrow-left.gif", "image/gif")]
[assembly: WebResource("EncyIG.Theme.arrow-right.gif", "image/gif")]
[assembly: WebResource("EncyIG.Theme.ArrowBkg.gif", "image/gif")]
[assembly: WebResource("EncyIG.Theme.Attach.gif", "image/gif")]
[assembly: WebResource("EncyIG.Theme.Attention.gif", "image/gif")]
[assembly: WebResource("EncyIG.Theme.BACK.gif", "image/gif")]
[assembly: WebResource("EncyIG.Theme.Bullet.gif", "image/gif")]
[assembly: WebResource("EncyIG.Theme.ButtonBg.gif", "image/gif")]
[assembly: WebResource("EncyIG.Theme.Calendar.gif", "image/gif")]
[assembly: WebResource("EncyIG.Theme.CategoryBg.gif", "image/gif")]
[assembly: WebResource("EncyIG.Theme.CheckMark.gif", "image/gif")]
[assembly: WebResource("EncyIG.Theme.CheckMark2.gif", "image/gif")]
[assembly: WebResource("EncyIG.Theme.CheckMarkLarge.GIF", "image/GIF")]
[assembly: WebResource("EncyIG.Theme.Close.gif", "image/gif")]
[assembly: WebResource("EncyIG.Theme.DataSheet.gif", "image/gif")]
[assembly: WebResource("EncyIG.Theme.Delete.gif", "image/gif")]
[assembly: WebResource("EncyIG.Theme.DropArrow.gif", "image/gif")]
[assembly: WebResource("EncyIG.Theme.DropArrowDark.gif", "image/gif")]
[assembly: WebResource("EncyIG.Theme.Edit.gif", "image/gif")]
[assembly: WebResource("EncyIG.Theme.EditMode.gif", "image/gif")]
[assembly: WebResource("EncyIG.Theme.Erase.gif", "image/gif")]
[assembly: WebResource("EncyIG.Theme.Excel.gif", "image/gif")]
[assembly: WebResource("EncyIG.Theme.EXCLAIM.gif", "image/gif")]
[assembly: WebResource("EncyIG.Theme.ExportCsv.gif", "image/gif")]
[assembly: WebResource("EncyIG.Theme.ExportRowset.gif", "image/gif")]
[assembly: WebResource("EncyIG.Theme.ExportRss.gif", "image/gif")]
[assembly: WebResource("EncyIG.Theme.Filter.gif", "image/gif")]
[assembly: WebResource("EncyIG.Theme.FilterOff.gif", "image/gif")]
[assembly: WebResource("EncyIG.Theme.FilterOffDisabled.gif", "image/gif")]
[assembly: WebResource("EncyIG.Theme.FORWARD.gif", "image/gif")]
[assembly: WebResource("EncyIG.Theme.HeaderBg.gif", "image/gif")]
[assembly: WebResource("EncyIG.Theme.html-editor-buttons.png", "image/png")]
[assembly: WebResource("EncyIG.Theme.ICONGO.gif", "image/gif")]
[assembly: WebResource("EncyIG.Theme.Import.png", "image/png")]
[assembly: WebResource("EncyIG.Theme.Import2.png", "image/png")]
[assembly: WebResource("EncyIG.Theme.Information.gif", "image/gif")]
[assembly: WebResource("EncyIG.Theme.Maximize.gif", "image/gif")]
[assembly: WebResource("EncyIG.Theme.MenuBg.gif", "image/gif")]
[assembly: WebResource("EncyIG.Theme.MenuBgLarge.gif", "image/gif")]
[assembly: WebResource("EncyIG.Theme.Minimize.gif", "image/gif")]
[assembly: WebResource("EncyIG.Theme.MultiPage.gif", "image/gif")]
[assembly: WebResource("EncyIG.Theme.Navigate.gif", "image/gif")]
[assembly: WebResource("EncyIG.Theme.NavStrip.gif", "image/gif")]
[assembly: WebResource("EncyIG.Theme.New.gif", "image/gif")]
[assembly: WebResource("EncyIG.Theme.NewLarge.gif", "image/gif")]
[assembly: WebResource("EncyIG.Theme.ObjectRef.gif", "image/gif")]
[assembly: WebResource("EncyIG.Theme.Paste.png", "image/png")]
[assembly: WebResource("EncyIG.Theme.PopupArrow.gif", "image/gif")]
[assembly: WebResource("EncyIG.Theme.Print.png", "image/png")]
[assembly: WebResource("EncyIG.Theme.QuickFind.gif", "image/gif")]
[assembly: WebResource("EncyIG.Theme.Refresh.png", "image/png")]
[assembly: WebResource("EncyIG.Theme.Save.gif", "image/gif")]
[assembly: WebResource("EncyIG.Theme.SaveLarge.gif", "image/gif")]
[assembly: WebResource("EncyIG.Theme.Search.gif", "image/gif")]
[assembly: WebResource("EncyIG.Theme.Search.png", "image/png")]
[assembly: WebResource("EncyIG.Theme.SearchPlusMinus.png", "image/png")]
[assembly: WebResource("EncyIG.Theme.SettingsGraphic.jpg", "image/jpg")]
[assembly: WebResource("EncyIG.Theme.SortAZ.gif", "image/gif")]
[assembly: WebResource("EncyIG.Theme.SortDown.gif", "image/gif")]
[assembly: WebResource("EncyIG.Theme.SortUp.gif", "image/gif")]
[assembly: WebResource("EncyIG.Theme.SortZA.gif", "image/gif")]
[assembly: WebResource("EncyIG.Theme.StatusBar.png", "image/png")]
[assembly: WebResource("EncyIG.Theme.syst-ui-bg_glass_65_ffffff_1x400.png", "image/png")]
[assembly: WebResource("EncyIG.Theme.syst-ui-icons_222222_256x240.png", "image/png")]
[assembly: WebResource("EncyIG.Theme.tab-active-left-verticalleft.gif", "image/gif")]
[assembly: WebResource("EncyIG.Theme.tab-active-left-verticalright.gif", "image/gif")]
[assembly: WebResource("EncyIG.Theme.tab-active-left.gif", "image/gif")]
[assembly: WebResource("EncyIG.Theme.tab-active-right-verticalleft.gif", "image/gif")]
[assembly: WebResource("EncyIG.Theme.tab-active-right-verticalright.gif", "image/gif")]
[assembly: WebResource("EncyIG.Theme.tab-active-right.gif", "image/gif")]
[assembly: WebResource("EncyIG.Theme.tab-active-verticalleft.gif", "image/gif")]
[assembly: WebResource("EncyIG.Theme.tab-active-verticalright.gif", "image/gif")]
[assembly: WebResource("EncyIG.Theme.tab-active.gif", "image/gif")]
[assembly: WebResource("EncyIG.Theme.tab-bottom-active-left.gif", "image/gif")]
[assembly: WebResource("EncyIG.Theme.tab-bottom-active-right.gif", "image/gif")]
[assembly: WebResource("EncyIG.Theme.tab-bottom-active.gif", "image/gif")]
[assembly: WebResource("EncyIG.Theme.tab-bottom-hover-left.gif", "image/gif")]
[assembly: WebResource("EncyIG.Theme.tab-bottom-hover-right.gif", "image/gif")]
[assembly: WebResource("EncyIG.Theme.tab-bottom-hover.gif", "image/gif")]
[assembly: WebResource("EncyIG.Theme.tab-bottom-left.gif", "image/gif")]
[assembly: WebResource("EncyIG.Theme.tab-bottom-right.gif", "image/gif")]
[assembly: WebResource("EncyIG.Theme.tab-bottom.gif", "image/gif")]
[assembly: WebResource("EncyIG.Theme.tab-hover-left-verticalleft.gif", "image/gif")]
[assembly: WebResource("EncyIG.Theme.tab-hover-left-verticalright.gif", "image/gif")]
[assembly: WebResource("EncyIG.Theme.tab-hover-left.gif", "image/gif")]
[assembly: WebResource("EncyIG.Theme.tab-hover-right-verticalleft.gif", "image/gif")]
[assembly: WebResource("EncyIG.Theme.tab-hover-right-verticalright.gif", "image/gif")]
[assembly: WebResource("EncyIG.Theme.tab-hover-right.gif", "image/gif")]
[assembly: WebResource("EncyIG.Theme.tab-hover-verticalleft.gif", "image/gif")]
[assembly: WebResource("EncyIG.Theme.tab-hover-verticalright.gif", "image/gif")]
[assembly: WebResource("EncyIG.Theme.tab-hover.gif", "image/gif")]
[assembly: WebResource("EncyIG.Theme.tab-left-verticalleft.gif", "image/gif")]
[assembly: WebResource("EncyIG.Theme.tab-left-verticalright.gif", "image/gif")]
[assembly: WebResource("EncyIG.Theme.tab-left.gif", "image/gif")]
[assembly: WebResource("EncyIG.Theme.tab-line.gif", "image/gif")]
[assembly: WebResource("EncyIG.Theme.tab-right-verticalleft.gif", "image/gif")]
[assembly: WebResource("EncyIG.Theme.tab-right-verticalright.gif", "image/gif")]
[assembly: WebResource("EncyIG.Theme.tab-right.gif", "image/gif")]
[assembly: WebResource("EncyIG.Theme.tab-verticalleft.gif", "image/gif")]
[assembly: WebResource("EncyIG.Theme.tab-verticalright.gif", "image/gif")]
[assembly: WebResource("EncyIG.Theme.tab.gif", "image/gif")]
[assembly: WebResource("EncyIG.Theme.TabsActiveTab.gif", "image/gif")]
[assembly: WebResource("EncyIG.Theme.TabsBar.gif", "image/gif")]
[assembly: WebResource("EncyIG.Theme.TabsInactiveTab.gif", "image/gif")]
[assembly: WebResource("EncyIG.Theme.TabsSelectedTab.gif", "image/gif")]
[assembly: WebResource("EncyIG.Theme.TaskBullet.gif", "image/gif")]
[assembly: WebResource("EncyIG.Theme.TreeControls.png", "image/png")]
[assembly: WebResource("EncyIG.Theme.Undo.gif", "image/gif")]
[assembly: WebResource("EncyIG.Theme.ViewNameBg.gif", "image/gif")]
[assembly: WebResource("EncyIG.Theme.Wait.gif", "image/gif")]
[assembly: WebResource("EncyIG.Theme.Word.gif", "image/gif")]
